#! /bin/bash

subnet="192.168.1.6"
function pkdeploy {
   echo Deploying to $1
   rsync -avzc --delete . root@$subnet$1:~/Umm/
   ssh root@$subnet$1 "find ~/Umm/ | xargs touch 2>/dev/null"
   ssh root@$subnet$1 "source /etc/profile; cd ~/Umm/Histogram/FaultTolerant/; make;"
}

hosts="0 1 2 3 4"
if [ ! -z $1 ]
then
   hosts=$1
fi

for i in $hosts
do
   pkdeploy $i
done
