#! /bin/bash

subnet="192.168.1.6"
function pkdeploy {
   echo Deploying to $1
   rsync -avzc --delete . root@$subnet$1:~/Umm/
   # ssh root@$subnet$1 "cd ~/Umm/Histogram/FaultTolerant/; make; make;"
}

for i in $(seq 0 4)
do
   pkdeploy $i
done
