#! /bin/sh

make -s

if [ ! -d TestOutput ]
then
    mkdir TestOutput
fi

Serial ../Tests/10000/10000.a ../Tests/10000/10000.b
mv hist.a hist.b hist.c result.out TestOutput/

for file in hist.a hist.b hist.c result.out
do
    echo "---- Testing $file --------------------------------------------------"
    diff -q ./TestOutput/$file ../Tests/10000/$file
done
