\newlabel{LabBT}
\newlabel{LabEP}
\newlabel{LabFT}
\newlabel{LabIS}
\newlabel{LabLU}
\newlabel{LabMG}
\newlabel{LabSP}
\newlabel{LabTable}
\newlabel{PiBT}
\newlabel{PiEP}
\newlabel{PiFT}
\newlabel{PiIS}
\newlabel{PiLU}
\newlabel{PiMG}
\newlabel{PiSP}
\newlabel{PiTable}
