#! /bin/sh

program=
hostprefix=
uname -a | grep -q "ARCH"
if [ $? -eq 0 ]
then
    program="/usr/local/bin/mpirun"
    hostprefix="pkhosts"
else
    program="mpirun -mca btl_tcp_if_include eth0"
    hostprefix="hosts"
fi

hostnum="4"
if [ ! -z "$1" ]
then
    hostnum=$1
fi
shift

for test in 10000 #100000 1000000 10000000
do
    if [ ! -d TestOutput ]
    then
        mkdir TestOutput
    fi

    testdir="../Tests/$test"

    if [ ! -f "$testdir/result.out" ]
    then
        continue
    fi

    echo "Checking time for test $test"
    echo "-----------------------------------"
    time $program --hostfile Hostfiles/$hostprefix$hostnum -quiet --quiet -q FaultTolerant ../Tests/$test/$test.a ../Tests/$test/$test.b FaultTolerant
    mv hist.a hist.b hist.c result.out TestOutput/

    for file in hist.a hist.b hist.c result.out
    do
        diff -q ./TestOutput/$file $testdir/$file > /dev/null 2>&1
        if [ $? -ne 0 ]
        then
            echo "Diff failure for $file"
            echo "---------------------------"
            #diff ./TestOutput/$file $testdir/$file
            echo
            failed="yes"
        fi
    done

    rm -r TestOutput/
    echo
done


if [ $failed ]
then
    echo "Tests failed."
else
    echo "Tests passed."
fi
