#! /bin/sh

function ssh_check
{
	ssh -o ConnectTimeout=5 -q $1 exit
	if [ $? -eq 0 ] ; then
		echo $1;
	fi
}

rooms="302"
if [ $# -ne 0 ]
then
	rooms=$@
fi

for room in $rooms
do
	for machine in {1..60}
	do
		printf -v server $room"x%02d" $machine
		ssh_check $server &
	done
done
wait
