#! /bin/sh

make -s

for test in 10000 100000 1000000 10000000
do

    if [ ! -d TestOutput ]
    then
        mkdir TestOutput
    fi

    testdir="../Tests/$test"

    if [ ! -f "$testdir/result.out" ]
    then
        continue
    fi

    echo "Checking output for test $test"
    echo "-----------------------------------"

    mpirun -mca btl_tcp_if_include eth0 --hostfile Hostfiles/hosts4 FaultTolerant $testdir/$test.a $testdir/$test.b Parallel
    mv hist.a hist.b hist.c result.out TestOutput/

    for file in hist.a hist.b hist.c result.out
    do
        diff -q ./TestOutput/$file $testdir/$file > /dev/null 2>&1
        if [ $? -ne 0 ]
        then
            echo "Diff failure for $file"
            echo "---------------------------"
            diff ./TestOutput/$file $testdir/$file
            echo
            failed="yes"
        fi
    done

    rm -r TestOutput/
    echo

done


if [ $failed ]
then
    echo "Tests failed."
else
    echo "Tests passed."
fi
