#! /bin/sh

make -s

for test in 10000 100000 1000000 10000000
do
    echo "Checking time for test $test"
    echo "-----------------------------------"
    time /usr/local/bin/mpirun --hostfile Hostfiles/pkhosts2 FaultTolerant ../Tests/$test/$test.a ../Tests/$test/$test.b NetworkBenchmark
    rm hist.a hist.b hist.c result.out
done
