#! /bin/sh

make -s

for file in pkhosts2 pkhosts3 pkhosts4
do
    for test in 1000000 #10000 100000 1000000 10000000
    do
        echo "Checking time for test $test for hosts $file"
        echo "-----------------------------------"
        time /usr/local/bin/mpirun --hostfile Hostfiles/$file FaultTolerant ../Tests/$test/$test.a ../Tests/$test/$test.b
        rm hist.a hist.b hist.c result.out
    done
done
