#! /bin/sh

make -s

if [ ! -d TestOutput ]
then
    mkdir TestOutput
fi

mpirun -mca btl_tcp_if_include eth0 --hostfile Hostfiles/hosts2 --quiet -q FaultTolerant ../Tests/10000/10000.a ../Tests/10000/10000.b 2>/dev/null
mv hist.a hist.b hist.c result.out TestOutput/

for file in hist.a hist.b hist.c result.out
do
    diff -q ./TestOutput/$file ../Tests/10000/$file > /dev/null 2>&1
    if [ $? -ne 0 ]
    then
        echo "Diff failure for $file"
        echo "---------------------------"
        diff ./TestOutput/$file ../Tests/10000/$file
        echo
        failed="yes"
    fi
done

rm -r TestOutput/

echo
if [ $failed ]
then
    echo "Tests failed."
else
    echo "Tests passed."
fi
